#!/bin/bash

#SBATCH --job-name=index_reference
#SBATCH --output=index_reference.log
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH -A molecolb
#SBATCH -p molecolb
#SBATCH --mem-per-cpu=8GB
#SBATCH --time=24:00:00
#SBATCH -E g.gouws@sheffield.ac.uk

# Navigate to working directory in which reference genome fasta or fastq file is located
cd /mnt/fastdata/bi1gg/omnic/reference

# Complete initial faidx index with samtools
samtools faidx 30044_10.asm.bp.p_ctg.fasta

# Use the index file to generate the genome file by printing the first two columns into a new file
cut -f1,2 30044_10.asm.bp.p_ctg.fasta.fai > Oceanic_cricket.genome

# Index the fasta file with bwa
bwa index 30044_10.asm.bp.p_ctg.fasta
